ilmer_cms:
    resource: "@IlmerCMSBundle/Resources/config/routing/routing.yml"
    prefix:   /

ilmer_user:
    resource: "@IlmerUserBundle/Controller/"
    type:     annotation
    prefix:   /

FOSUserBundle:
    resource: "@IlmerUserBundle/Resources/config/routing/routing.xml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal


